### ISSUE TITLE
Input.npy not found

### ISSUE THREAD

**Issue by martanto** [ZahraZali/ClusTremor#1]
Hello, I am trying to reproduce the jupyter notebook that you were shared.
Unfortunately I can not find an example file named 'Input.npy' 

![image](https://github.com/ZahraZali/ClusTremor/assets/13482145/7fc5d096-0b40-4abf-bd9f-6ec683c46e7f)

Thank you.

**Comment by Haoran-DONG** [comment]
Hello, I am also experiencing difficulty in finding the "Input.npy" file. I would appreciate it if more detailed instructions could be provided. Thank you!

**Comment by ZahraZali** [comment]
Thank you for your comments. I've added the Input.npy file to the repository in the src folder, where the code requires it. Please remember to cite the original data and any derived results if you use them.
